### ISSUE TITLE
Could support game image and region hk?

### ISSUE THREAD

**Issue by MagicCodess** [fedecalendino/nintendeals#10]
A good project, could it support game surface image url and information from rigion of hk?

**Comment by fedecalendino** [comment]
I'll see what I can do. Last time I checked it wasn't possible, hopefully this time around nintendo improved their HK stores.

**Comment by mariomadproductions** [comment]
I think both Nintendo HK and KR have improved their site.
E.g. it seems you can get the relevant info for BOTW's KR/HK nsuid with these urls:
https://store.nintendo.com.hk/70010000009367
https://store.nintendo.co.kr/70010000009367

**Comment by fedecalendino** [comment]
Hi!

At the moment, I'm not planning on adding new regions to the library.

But I'll happily accept PRs for them if you want to give it a try.


Cheers,
Fede.
