### ISSUE TITLE
product_code returns an int value which was defined as string

### ISSUE THREAD

**Issue by zackaryhuang** [fedecalendino/nintendeals#11]
![eda53d7d7c7f8ace8c02066929e539b](https://user-images.githubusercontent.com/31388697/200179381-b3f2ec43-946d-4086-a455-22206abddf59.png)

and also, nsuid returns an int value which was defined as string
![image](https://user-images.githubusercontent.com/31388697/200179704-65c622af-a7f3-4c40-aacb-d3fb8b2d9442.png)

**Comment by fedecalendino** [comment]
Fixed on v3.0.1
