### ISSUE TITLE
No luck getting game data from NOA for Metroid Prime Remastered or Octopath Traveler II for example

### ISSUE THREAD

**Issue by nemecek-filip** [fedecalendino/nintendeals#14]
Hello,

I hoped I wouldn't have to open an issue but I cannot get NOA integration to work.

I tried it with a couple of new games Metroid Prime Remastered (NSUID: `70010000063709`) and Octopath Traveler II (NSUID `70010000058128` but I always get back `None`.

When investigating further, I found that the issue seem to be in `game_info_by_nsuid` when this is called `data = algolia.search_by_nsuid(nsuid)` 

And bellow it returns `None` because the data couldn't be found.

I also tried the `scrap` method available for NOA and this works. I can get the `nsuid` and then use the prices API to get the info on NOA.

Is something wrong with the algolia at the moment? 

I am open to trying to fix this issue if you can point me to the right direction.

**Comment by fedecalendino** [comment]
Dobrý večer!

I'll give it a quickly look tomorrow. Sometime is just that Nintendo rotated their Algolia API Key.

I'll let you know.

Fede.

**Comment by fedecalendino** [comment]
Hi again!

I've been trying to fix the problem, but it seems that the new index in algolia has removed the search function for some reason.

In the meantime, you can use this values to fetch the data of the new games:


https://github.com/fedecalendino/nintendeals/blob/main/nintendeals/noa/api/algolia.py#L7

```
APP_ID = "U3B6GR4UA3"
API_KEY = "a29c6927638bfd8cee23993e51e721c9"

INDEX_NAME = "store_game_en_us"
```


I'll try later this week to investigate to see if I can find a way to re add some of the broken features back in to the library.

Cheers,
Fede.

**Comment by nemecek-filip** [comment]
Thanks for the super quick responses! 

It seems like Algolia stopped indexing new games? I tried the new version and while the recent games still don't seem to work, I am able to query and also get details for older titles. I just tried Metroid Dread, (nsuid: `70010000042924`) and that works on NOA.

Not sure if it's related but querying Bayonetta 3 works on NAO, but the `Game` doesn't have `nsuid` however it has all the other data.

![image](https://user-images.githubusercontent.com/49204469/221660264-fc9fd753-b3b5-4c5a-8d8f-377b32e04964.png)

**Comment by fedecalendino** [comment]
Hi! You also need to change the index to `INDEX_NAME = "store_game_en_us"`. Seems the old one is outdated.

**Comment by nemecek-filip** [comment]
Yea, I updated the package but didn't help. Perhaps there is 🐛  in my debug code it grew quite a bit :D

Will look at it again tomorrow with fresh eyes.

**Comment by nemecek-filip** [comment]
Finally got to it after being sick.. 

Created brand new Python project but I cannot get the new index to work at all.

This is my testing code:

```
from nintendeals import noa

for game in noa.search_switch_games(query="Bayonetta 3"):
    print(game.title, "/", game.nsuid)

for game in noa.search_switch_games(query="Zelda"):
    print(game.title, "/", game.nsuid)
```

And with the `INDEX_NAME = "ncom_game_en_us"` I get this output:

> Bayonetta™ 3 / None
> Game & Watch™: The Legend of Zelda™ / None
> The Legend of Zelda™: Skyward Sword HD / 70010000038612
> The Legend of Zelda™: Link’s Awakening / 70010000020033
> Cadence of Hyrule: Crypt of the NecroDancer Featuring The Legend of Zelda / 70010000021364
> The Legend of Zelda™: Breath of the Wild / 70010000000025

When I update the `algolia.py` to have new index: `INDEX_NAME = "store_game_en_us"` the output is empty - it looks like it is not able to find any games.

**Comment by nemecek-filip** [comment]
@fedecalendino does the result above tracks with what you are seeing or is there a problem in my usage?

**Comment by nemecek-filip** [comment]
@fedecalendino hi!

I also found this index name `store_all_products_en_us` in one npm package (https://www.npmjs.com/package/nintendo-switch-eshop?activeTab=code) but it doesn't list any games.

Are there alternative sources? Sites like DekuDeals seem to work just fine for US Eshop

**Comment by fedecalendino** [comment]
Hi Filip!

Sorry for the radio silence, I'm in the middle of a house move so I haven't been able to focus on this.

As far as a I know the dev of DekuDeals is a cool guy, might be worth reaching out to him for some ideas.

I'll try to get back on this as soon as I settled in my new home.

Cheers,
Fede.

**Comment by nemecek-filip** [comment]
Thanks for the heads up! No worries!

I have tried to reach out to Michael from DekuDeals a while back but haven't heard back.

My current progress is that I managed to get NSUIDs for around 7K games from the NOA with the old index and new key. For the rest I plan to get store links from the website and then use the `scrap` method to get the NSUIDs for the remaining games.

**Comment by bp32795** [comment]
I think I am having a similar bug with `noa.game_info(nsuid)`

```
>>> noa.game_info("70010000016383") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bp327\AppData\Roaming\Python\Python310\site-packages\nintendeals\noa\info.py", line 64, in game_info
    return game_info_by_nsuid(nsuid)
  File "C:\Users\bp327\AppData\Roaming\Python\Python310\site-packages\nintendeals\noa\info.py", line 15, in game_info_by_nsuid
    data["extra"] = nintendo.scrap(data["slug"])
  File "C:\Users\bp327\AppData\Roaming\Python\Python310\site-packages\nintendeals\noa\scrapers\nintendo.py", line 21, in scrap
    languages = next(h3.nextSiblingGenerator())
AttributeError: 'NoneType' object has no attribute 'nextSiblingGenerator'
```

Is this the same error as you two are getting or something different?

**Comment by nemecek-filip** [comment]
@bp32795 hi, this seems to be something different, take a look at this PR - https://github.com/fedecalendino/nintendeals/pull/15

Some of the NOA websites don't have all the data the scrapping logic expects

**Comment by bp32795** [comment]
Gotcha, thank you. Is there anyway to scrape what game info it does have or is it not possible with the current library?

**Comment by nemecek-filip** [comment]
As for now, I think you'd need to update the scrapping code to mainly handle missing data.

**Comment by bp32795** [comment]
Okay, so now weirdly if I run that same command, it fails in a different place: 
```
>>> noa.game_info("70010000016383") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bp327\AppData\Roaming\Python\Python310\site-packages\nintendeals\noa\info.py", line 64, in game_info
    return game_info_by_nsuid(nsuid)
  File "C:\Users\bp327\AppData\Roaming\Python\Python310\site-packages\nintendeals\noa\info.py", line 15, in game_info_by_nsuid
    data["extra"] = nintendo.scrap(data["slug"])
  File "C:\Users\bp327\AppData\Roaming\Python\Python310\site-packages\nintendeals\noa\scrapers\nintendo.py", line 18, in scrap
    data = json.loads(script.text)["props"]["pageProps"]["product"]
KeyError: 'product'
```
Any idea? Did something change on nintendo's end?

**Comment by nemecek-filip** [comment]
I just looked into my backend and I have this game imported from end of April and also have some NOA games from later date.

Do other games work? It is possible you ran the script too many times and it sometimes doesn't return the data?

**Comment by bp32795** [comment]
Also tried to do 
```
    try:
        data = json.loads(script.text)["props"]["pageProps"]["analytics"]["product"]
    except Exception as e:
        print(e)
```
But it never makes it inside the try block for some reason. Gets right up to it and then returns and breaks.

**Comment by nemecek-filip** [comment]
@bp32795 take a look at this: https://github.com/fedecalendino/nintendeals/issues/17

**Comment by bp32795** [comment]
@nemecek-filip, yep that sounds like my problem too. I was in the process of modifying your code to match the new format, but if you are already working on it, I will wait for a release.

**Comment by fedecalendino** [comment]
Hello! Long time no see, sorry for the massive delay.

I just updated the library to v3.1.0 (https://github.com/fedecalendino/nintendeals/releases/tag/v3.1.0) which should work for this new games and the new algolia index.

Please let me know if this works for you.

Cheers,
Fede

**Comment by nemecek-filip** [comment]
@fedecalendino awesome welcome back 🙌

Looking at the commits it seems Nintendo changed things quite a bit..
