### ISSUE TITLE
Issue parsing product from new Nintendo JSON format

### ISSUE THREAD

**Issue by ScottHacksIt** [fedecalendino/nintendeals#17]
Hello! It seems like Nintendo may have changed their game info JSON structure, I'm attaching a sample of it as it downloaded for me (Breath.of.the.Wild.data.txt). In the Nintendo.py scrap() method, there was an exception looking for the "product" element.

<code>soup = BeautifulSoup(response.text, features="html.parser")
script = soup.find("script", id="__NEXT_DATA__")
data = json.loads(script.text)["props"]["pageProps"]["product"]</code>

I locally replaced the block of code with this and it works:
<code>soup = BeautifulSoup(response.text, features="html.parser")
script = soup.find("script", id="__NEXT_DATA__")
linkedData = json.loads(script.text)["props"]["pageProps"]["linkedData"]
sku = linkedData["sku"]
productElement = "StoreProduct:{\"sku\":\"" + sku + "\",\"locale\":\"en_US\"}"
data = json.loads(script.text)["props"]["pageProps"]["initialApolloState"][productElement]</code>

Thanks for this awesome library!
[Breath of the Wild data.txt](https://github.com/fedecalendino/nintendeals/files/11738423/Breath.of.the.Wild.data.txt)

**Comment by nemecek-filip** [comment]
Damn, thanks for the report. I need to check my importing logic asap.

**Comment by fedecalendino** [comment]
Hi!

this should be fixed on v3.1.0.

Let me know if it works for you.

Cheers, Fede.

**Comment by ScottHacksIt** [comment]
The latest version works perfectly. Interesting that list_switch_games() now finds around 2,000 more games! Thanks for the fix!
