### ISSUE TITLE
Can not get unique_id or product_code for noa.game_info

### ISSUE THREAD

**Issue by zackaryhuang** [fedecalendino/nintendeals#18]
Same code as your readme file
<img width="1101" alt="image" src="https://github.com/fedecalendino/nintendeals/assets/31388697/8573e5bf-cdfc-4bd8-961a-fdc63169dd5c">
but the product_code and unique_id are None

**Comment by fedecalendino** [comment]
Hi!

this should be fixed on v3.1.0.

Let me know if it works for you.

Cheers, Fede.
