### ISSUE TITLE
Nintendo API rate limits?

### ISSUE THREAD

**Issue by nemecek-filip** [fedecalendino/nintendeals#19]
Hello,

today I discovered that my prices import started failling due to 403. Seems like my server IP got blocked from accessing `https://api.ec.nintendo.com/v1/price`. I had import for around 10 countries that run once a day with `sleep` sprinkled in to not make too many requests in quick succession.

Has anyone run into something similar?

**Comment by fedecalendino** [comment]
Hi!

I wasn't aware of this but I'm not fully surprised rate limiting APIs is a normal practice. 

Do you know around how many requests this happens?

Cheers,
Fede.

**Comment by nemecek-filip** [comment]
After some investigations it appears to be broad IP address block. I tried test API call from my Digital Ocean VPS which I use for other projects and it was immediate 403. Same with Contabo provider from Germany.

Seems like Akamai blocked the access - going by the HTML error message with case number that is returned.

I am currently running the import from other IP that works with a bit more `sleep`s and seems to work fine.
