### ISSUE TITLE
NOA crash when getting game info for "Bunny Park", `platform` key issue

### ISSUE THREAD

**Issue by nemecek-filip** [fedecalendino/nintendeals#20]
Hello,

I have noticed interesting issue with the `noa.game_info` when fetching data for this game: https://www.nintendo.com/us/store/products/bunny-park-switch/. Its nsuid is "70010000052765".

```python
bunny_game = noa.game_info(nsuid="70010000052765")
```

It crashes in the `build_game` method when attempting to get the platform: `platform=PLATFORMS[data["platform"]],`.

For some reason, the platform that is included for this game is: "'Nintendo Switch – OLED Model'" and not simply "Nintendo Switch" and therefore the dictionary lookup throws `KeyError`.

The key `corePlatforms` correctly has "Nintendo Switch" entry.

I think maybe extending the `PLATFORMS` model like this would work?

```python
PLATFORMS = {
    "Nintendo Switch": Platforms.NINTENDO_SWITCH,
    "Nintendo Switch – OLED Model": Platforms.NINTENDO_SWITCH
}
```

**Comment by fedecalendino** [comment]
That is weird, I wonder if that is an OLED exclusive.

Yeah, that should work. Do you want to post a PR with the change?

I'll release a version after that.

**Comment by nemecek-filip** [comment]
I checked the NOE webpage of the game and nothing suggests it being a OLED exclusive, so probably just some sort of data inconsistency in their admin..

Will submit the PR shortly.
