### ISSUE TITLE
product_code and unique_id return " None "

### ISSUE THREAD

**Issue by best3140** [fedecalendino/nintendeals#9]
Pitupongs-Air:~ Best3140$ python3 testNin1.py 
The Legend of Zelda™: Breath of the Wild
None None
2017-03-03 00:00:00
1
ESRB Everyone 10+
https://www.nintendo.com/fr_CA/games/detail/the-legend-of-zelda-breath-of-the-wild-switch
 * Demo Available : False
 * DLC Available : True
 * Nintendo Switch Online Required : True
 * Save Data Cloud Supported : True
Pitupongs-Air:~ Best3140$

**Comment by fedecalendino** [comment]
Hi @best3140, sorry for the late response.

Sadly, nintendo has removed the product code from the NA eshop sites so there is no way for me to fetch it. Also, since the unique_id is constructed based on that code, that one is also unavailable.

**Comment by best3140** [comment]
many thanks, hope you can find the way soon ^^
